<?php

namespace Client\Services\LangService;

class Text
{
    public static function get(string $key)
    {
        return self::MESSAGES[Resolver::getLang()][$key];
    }

    private const MESSAGES = [
        ILang::RU => [
            'mainTitle' => 'Знакомства',
            'mainSubtitle' => 'Для разного формата отношений',
            'mainDesc' => '🔒 Переписки и личные данные защищены',
            'signIn' => 'Вход',
            'signUp' => 'Регистрация',
            'search' => 'Поиск',
            'visitsTitle' => 'Просмотры Вашего профиля',
            'chooseChat' => 'Выберите диалог',
            'chatStub' => 'Выберите диалог или создайте новый. Начать новый диалог можно на странице интересующего пользователя',
            'you' => 'Вы',
            'image' => 'Изображение',
            'send' => 'Отправить',
            'wallet' => 'Кошелек',
            'putMoney' => 'Пополнить',
            'rub' => 'руб',
            'activate' => 'Активировать',
            'profileSettings' => 'Настройки профиля',
            'women' => 'Девушки',
            'men' => 'Мужчины',
            'datingGoals' => 'Цели знакомства',
            'userAbout' => 'О себе',
            'myPhotos' => 'Мои фото',
            'personalInfo' => 'Личная информация',
            'changePassword' => 'Сменить пароль',
            'add' => 'Добавить',
            'save' => 'Сохранить',
            'heWasOnline' => 'Был в сети',
            'sheWasOnline' => 'Была в сети',
            'show' => 'Показать',
            'age' => 'Возраст',
            'find' => 'Найти',
            'city' => 'Город',
            'ISearchWoman' => '👩 Девушку',
            'ISearchMan' => '👨 Мужчину',
            'from' => 'от',
            'to' => 'до',
            'partnerGoals' => 'Цели партнера',
            'next' => 'Продолжить',
        ],
        ILang::EN => [
            'mainTitle' => 'Dating',
            'mainSubtitle' => 'For a different format of relations',
            'mainDesc' => '🔒 Correspondence and personal data are protected',
            'signIn' => 'Sign in',
            'signUp' => 'Sign up',
            'search' => 'Search',
            'visitsTitle' => 'Profile visits',
            'chooseChat' => 'Choose chat',
            'chatStub' => 'Select a dialogue or create a new one. You can start a new dialogue on the page of the user of interest.',
            'you' => 'You',
            'image' => 'Image',
            'send' => 'Send',
            'wallet' => 'Wallet',
            'putMoney' => 'Put money',
            'rub' => 'rub',
            'activate' => 'Activate',
            'profileSettings' => 'Profile settings',
            'women' => 'Women',
            'men' => 'Men',
            'datingGoals' => 'Dating goals',
            'userAbout' => 'About',
            'myPhotos' => 'My photos',
            'personalInfo' => 'Personal info',
            'changePassword' => 'Change password',
            'add' => 'Add',
            'save' => 'Save',
            'heWasOnline' => 'Was online',
            'sheWasOnline' => 'Was online',
            'show' => 'Show',
            'age' => 'Age',
            'find' => 'Find',
            'city' => 'City',
            'ISearchWoman' => '👩 Woman',
            'ISearchMan' => '👨 Man',
            'from' => 'from',
            'to' => 'to',
            'partnerGoals' => 'Partner goals',
            'next' => 'Next',
        ]
    ];
}
