<?php

return [
    // woman
    [
        'name'         => 'Ангелина',
        'email'        => 'angelina@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 18,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Мальчики пишите первые',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Светлана',
        'email'        => 'svetlana@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 22,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Ищу мужчину для отношений, важно чтобы меня уважал',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Маша',
        'email'        => 'mashs@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 24,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Ищу мужчину для отношений, важно чтобы меня уважал',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Юля',
        'email'        => 'yulya@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 23,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Ищу мужчину для отношений, важно чтобы меня уважал',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Настя',
        'email'        => 'nastya@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 40,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Ищу мужчину для отношений, важно чтобы меня уважал',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Евгения',
        'email'        => 'evgenya@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 35,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Хочу провести вечер с состоятельным мужчиной',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Мари',
        'email'        => 'mari@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 31,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Хочу провести вечер с состоятельным мужчиной',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Milayamiss',
        'email'        => 'milayamiss@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 29,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Хочу провести вечер с состоятельным мужчиной',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Good girl',
        'email'        => 'goodgirl@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 18,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Интересуют прежде всего продолжительные отношения',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Незнакомка',
        'email'        => 'neznakomka@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 19,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Интересуют прежде всего продолжительные отношения',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Александра',
        'email'        => 'aleksandra@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 19,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Интересуют прежде всего продолжительные отношения',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'София',
        'email'        => 'sofia@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 22,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Angel',
        'email'        => 'angel@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 22,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Твоя мечта',
        'email'        => 'yourdream@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 22,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Сонечка',
        'email'        => 'sonechka@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 25,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Твой наркотик',
        'email'        => 'yourdrug@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 25,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Привет. Я много читаю, говорю на английском и испанском языках. Люблю путешествовать. Не хочешь составить мне компанию?',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Ангелина',
        'email'        => 'angelina2@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 31,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => 'Привет. Я много читаю, говорю на английском и испанском языках. Люблю путешествовать. Не хочешь составить мне компанию?',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Мадина',
        'email'        => 'madina@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 31,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Камилла',
        'email'        => 'kamilla@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 22,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Анастасия',
        'email'        => 'anastasia2@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 22,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Солнечная',
        'email'        => 'sunny@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 22,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Сашка',
        'email'        => 'sashka@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 37,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Mommy',
        'email'        => 'mommy@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 37,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Soft girl',
        'email'        => 'softgirl@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 37,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Солнце',
        'email'        => 'sun@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 37,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Афоня',
        'email'        => 'afonya@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 37,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Sara Gold',
        'email'        => 'saragold@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 37,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Jessica',
        'email'        => 'jessica@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 37,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Путешественница',
        'email'        => 'traveller@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 37,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Рыжуля',
        'email'        => 'rizhulya@ankira-test.ru',
        'sex'          => 'woman',
        'age'          => 37,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],

    // man
    [
        'name'         => 'Big cock',
        'email'        => 'bigcock@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 37,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Iron Eagle',
        'email'        => 'ironeagle@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 37,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Саня',
        'email'        => 'sanya@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 29,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Богач',
        'email'        => 'bogach@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 29,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Шкод',
        'email'        => 'shkod@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 29,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Пенетратор',
        'email'        => 'penetrator@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 25,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Алекс',
        'email'        => 'alex@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 25,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'John',
        'email'        => 'john@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 25,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Сергей',
        'email'        => 'sergey@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 25,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Женя',
        'email'        => 'jenya2@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 45,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Страус',
        'email'        => 'straus@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 45,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Пикачу',
        'email'        => 'pikachu@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 45,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Зубарев',
        'email'        => 'zubarev@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 45,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Алексей',
        'email'        => 'alexey@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 45,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Vitaly',
        'email'        => 'vitaly@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 45,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'original boy',
        'email'        => 'originalboy@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 34,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Кавказский мачо',
        'email'        => 'kavkazkiymacho@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 34,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Суперспортик',
        'email'        => 'supersportik@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 34,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Аяз',
        'email'        => 'ayaz@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 31,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Фил',
        'email'        => 'phil@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 31,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Андрей К.',
        'email'        => 'andreyk@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 31,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
    [
        'name'         => 'Саша',
        'email'        => 'sasha3@ankira-test.ru',
        'sex'          => 'man',
        'age'          => 23,
        'city'         => 'Москва',
        'passwordHash' => hash('sha256', 123456),
        'about'        => '',
        'createdAt'    => date('Y-m-d H:i:s'),
    ],
];
